### ISSUE TITLE
Problems with peewee and vorta v0.6.18 on Fedora 29

### ISSUE THREAD

**Issue by conor-byrne** [borgbase/vorta#266]
**Describe the bug**
Crashes on launch

**To Reproduce**
1. install via `pip3 install vorta --user`
2. run `vorta`
3. view error stack trace
```
Traceback (most recent call last):
  File "/home/cbyrne/.local/bin/vorta", line 11, in <module>
    load_entry_point('vorta==0.6.18', 'gui_scripts', 'vorta')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/cbyrne/.local/lib/python3.7/site-packages/vorta/__main__.py", line 6, in <module>
    from vorta.models import init_db
  File "/home/cbyrne/.local/lib/python3.7/site-packages/vorta/models.py", line 114, in <module>
    class ArchiveModel(pw.Model):
  File "/home/cbyrne/.local/lib/python3.7/site-packages/vorta/models.py", line 118, in ArchiveModel
    repo = pw.ForeignKeyField(RepoModel, backref='archives')
  File "/home/cbyrne/.local/lib/python3.7/site-packages/peewee.py", line 1256, in __init__
    super(ForeignKeyField, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'backref'
```

**Desktop (please complete the following information):**
 - OS: Fedora 29

**Additional context**
It was working, then I installed some other packages via pip and something broke.
I've tried reinstalling but get the same issue.

**Comment by m3nu** [comment]
Thanks for reporting. This error happens in [peewee](https://github.com/coleifer/peewee/blob/master/peewee.py), the database ORM we use. It should clearly know the `backref` argument. It's documented rather well.

What's your version of Peewee? (`pip3 freeze | grep peewee`)

Does updating Peewee resolve the issue (`pip3 -U --user peewee`)

**Comment by conor-byrne** [comment]
Yup, updating peewee fixed it. Not sure what downgraded it but anyhow, issue solved!
Thanks!

**Comment by Hofer-Julian** [comment]
I also have problems with peewee on Fedora 29, but only for v0.6.18. When I upgrade to v0.6.17 everything works fine.

```
Traceback (most recent call last):
  File "/home/julian/git-projects/Vorta-Test/env/lib64/python3.7/site-packages/peewee.py", line 2936, in execute_sql
    cursor.execute(sql, params or ())
sqlite3.OperationalError: incomplete input

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/julian/git-projects/Vorta-Test/env/bin/vorta", line 11, in <module>
    load_entry_point('vorta', 'gui_scripts', 'vorta')()
  File "/home/julian/git-projects/Vorta-Test/vorta/src/vorta/__main__.py", line 29, in main
    init_db(sqlite_db)
  File "/home/julian/git-projects/Vorta-Test/vorta/src/vorta/models.py", line 351, in init_db
    ArchiveModel.insert_many(data, fields=fields).execute()
  File "/home/julian/git-projects/Vorta-Test/env/lib64/python3.7/site-packages/peewee.py", line 1778, in inner
    return method(self, database, *args, **kwargs)
  File "/home/julian/git-projects/Vorta-Test/env/lib64/python3.7/site-packages/peewee.py", line 1849, in execute
    return self._execute(database)
  File "/home/julian/git-projects/Vorta-Test/env/lib64/python3.7/site-packages/peewee.py", line 2567, in _execute
    return super(Insert, self)._execute(database)
  File "/home/julian/git-projects/Vorta-Test/env/lib64/python3.7/site-packages/peewee.py", line 2316, in _execute
    cursor = database.execute(self)
  File "/home/julian/git-projects/Vorta-Test/env/lib64/python3.7/site-packages/peewee.py", line 2949, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/home/julian/git-projects/Vorta-Test/env/lib64/python3.7/site-packages/peewee.py", line 2943, in execute_sql
    self.commit()
  File "/home/julian/git-projects/Vorta-Test/env/lib64/python3.7/site-packages/peewee.py", line 2725, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/home/julian/git-projects/Vorta-Test/env/lib64/python3.7/site-packages/peewee.py", line 183, in reraise
    raise value.with_traceback(tb)
  File "/home/julian/git-projects/Vorta-Test/env/lib64/python3.7/site-packages/peewee.py", line 2936, in execute_sql
    cursor.execute(sql, params or ())
peewee.OperationalError: incomplete input
```
Upgrading peewee doesn't help, also `pip3 -U --user peewee` gives `no such option: -U`.


@m3nu Any ideas where this could come from?

**Comment by m3nu** [comment]
0.6.18 migrates the archive table because someone wanted to link the same repo multiple times. So I had to copy all the data to a new table to get rid of the constraint. (sqlite doesn't allow changing existing tables)

Your error seems to happen there. Could be a very large archive table? In that case some paging could help, like [here](https://stackoverflow.com/a/36788489/3983708).

(The command above should be `pip3 install -U peewee`)

**Comment by m3nu** [comment]
Here a PR that copies large tables in chunks. I only have 200 rows, so mine will always work. Several thousand may give issues. We can reduce the `size=1000` if needed.

**Comment by Hofer-Julian** [comment]
PR #267 fixes it for me, thanks :)
