### ISSUE TITLE
Issues with initalizing a repository

### ISSUE THREAD

**Issue by AIKsuger** [borgbase/vorta#894]
**Describe the bug**
While trying to add a new repository to sync with a BorgBase on the macos Vorta app I received the following message:

Uncaught exception, please file a report with this text at
https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "views/repo_add_dialog.py", line 114, in run
  File "borg/init.py", line 19, in prepare
  File "borg/borg_thread.py", line 131, in prepare
AttributeError: 'Repo' object has no attribute 'is_remote_repo'

I am using Borgbase to host my repository. I followed the Youtuber Sun Knudsen's guide on setting it up. 

**To Reproduce**

**Environment (please complete the following information):**
- OS: MacOS Big sur
- Vorta version: v.0.7.3 
- Installed from: tried both with installing from the github repository directly and also via Homebrew

Vorta and Borg versions can be found in Main Window > Misc Tab.

**Additional context**
If appropriate include logs. Can be found in Main Window > Misc Tab > Log.

All the best and keep up the amazing work you do!

**Comment by m3nu** [comment]
Already resolved by #887. Please try current master branch.

**Comment by lamixer** [comment]
This bug hit me today as well. I wanted to do some work with Vorta today and 0.7.4 is not available from Homebrew yet, which is how I installed it.

Sorry for asking a fairly basic question, but I don't want to create problems for my Homebrew set up (or my current Vorta configs) but I would like to install 0.7.4 asap. Is there a safe way to do it, after which Homebrew will still continue to update Vorta?

I see I could download the .dmg from Github and drag it to replace the Vorta app in my Applications folder. I could also use Pip maybe, though I have no experience with that.

I know this question is a bit meta and not specifically vorta-related so thank you for any help.

**Comment by m3nu** [comment]
No problem to just copy a release downloaded from Github over the Homebrew-installed app. They are the same.
