### ISSUE TITLE
Crash on missing Wifi interface

### ISSUE THREAD

**Issue by phmg701** [borgbase/vorta#2140]
### Description

After updating **from the App itselft** to 0.10.1 it stopped working.
I then backed up my config and uninstalled from brew both borgbackup and vorta packages. Then and reinstalled following the usual instructions that worked the first time.
Now I get this error:

```
OS: Darwin
Release: 23.6.0
Version: Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:00 PDT 2024; root:xnu-10063.141.2~1/RELEASE_X86_64
Date and Time: 2024-11-18 08:28:27
Borg Version: 1.1.0
Vorta Version: 0.10.1
Traceback (most recent call last):
  File "application.py", line 113, in create_backup_action
  File "borg/create.py", line 127, in prepare
  File "network_status/darwin.py", line 14, in is_network_metered
AttributeError: 'NoneType' object has no attribute 'lastNetworkJoined'
```

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

MacOS Sonoma 14.6.1 (23G93)

### Version of Vorta

0.10.1

### What did you install Vorta with?

Homebrew

### Version of Borg

1.1.0

### Logs

```
2024-11-18 08:28:27,626 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new/choose
Traceback (most recent call last):
  File "application.py", line 113, in create_backup_action
  File "borg/create.py", line 127, in prepare
  File "network_status/darwin.py", line 14, in is_network_metered
AttributeError: 'NoneType' object has no attribute 'lastNetworkJoined'
```

**Comment by m3nu** [comment]
This means that Vorta can't find your Wifi interface. What's your networking setup like? We may need a check to deal with a situation of a missing Wifi. I don't see this handled currently.

**Comment by phmg701** [comment]
Oh, I found a bug! I have non WiFi, it's a desktop setup with just GbE connected to a Powerline.
Why did previous version work? How can I get back on track until the bug is fixed?
Thanks!

**Comment by m3nu** [comment]
Yes, congrats!

I'm doing a test build for macos you can use and test. My macbook has wifi, so can't test it.

You can grab it here: https://files.pf7.net/vorta/Vorta-issue2140.dmg

**Comment by phmg701** [comment]
I may have omitted I'm still on x86_64, sorry! This binary is AARCH64 and I can't test it.

**Comment by m3nu** [comment]
No problem. Here for Intel:

https://files.pf7.net/vorta/Vorta-issue2140-intel.dmg

**Comment by phmg701** [comment]
Works flawlessly, thank you!
